name: Deploy Backend

on:
  push:
    branches:
      - prod-backend

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod-backend
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm i
      - run: npm start backend
